sudo: false
language: node_js

node_js:
  - '10.0'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - npm update
install:
  - npm install
script:
  - npm test
