language: node_js
node_js:
  - '10.0'

dist: trusty
sudo: false
install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  - npm run lh -- https://nordgarden.michielkoning.nl/
