#import "./Fragments/Post.gql"
#import "./Fragments/Seo.gql"
#import "./Fragments/FeaturedImage.gql"

query GetPost($uri: ID!) {
  post(id: $uri, idType: URI) {
    ...post
    databaseId
    content
    seo {
      ...seo
    }
    featuredImage {
      ...featuredImage
    }
  }
}
