#import "./Fragments/Post.gql"
#import "./Fragments/FeaturedImage.gql"

query GetPosts($after: String, $notIn: [ID]) {
  posts(first: 12, after: $after, where: { notIn: $notIn }) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...post
        id
        slug
        excerpt
        featuredImage {
          ...featuredImage
        }
      }
    }
  }
}
